name: docs_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_custom_clippers: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/HealthProductImage.png
    - assets/images/docs_app_Gold.png
    - assets/images/discount_lab.jpeg
    - assets/images/docsapp_gold.jpeg
    - assets/images/above_mens.jpeg
    - assets/images/below_40
    - assets/images/below_girls.jpg
    - assets/images/womens_above40.jpg
    - assets/images/ebooks_img.jpeg
    - assets/images/booksImage.jpeg
    - assets/images/unnamed.jpg
    - assets/images/whatsap.png
    - assets/images/wight_plan.jpg
    - assets/images/refer_earn.jpeg
    - assets/images/lab_test.jpg
    - assets/images/doctors.jpg
    - assets/images/hair_los.jpg
    - assets/images/mensday_int.jpg
    - assets/images/female_above40.jpg
    - assets/images/below40_feamle.jpeg
    - assets/images/above_40mens.jpg
    - assets/images/medicine_delvery_boy.jpg
    - assets/images/consult.jpg
    - assets/images/powered_by.png
    - assets/images/logo.png
